import {teams} from './data';
import {sessionTeams,defaultSeedAssignments,validateSeedAssignments} from './seedAssignments';
import {gameProbability,seriesProbability} from './ratings';
import {worlds2026} from './worlds2026';
import type {Match,SimulationSession,TournamentState,TierList,StrengthSource,Stage} from './types';

const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
export function randomNext(session:SimulationSession):number { session.rngState=(Math.imul(session.rngState,1664525)+1013904223)>>>0;return session.rngState/4294967296 }
const shuffle=(ids:string[],s:SimulationSession)=>{const a=[...ids];for(let i=a.length-1;i>0;i--){const j=Math.floor(randomNext(s)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export function makeMatch(s:SimulationSession,id:string,stage:Stage,round:number,label:string,a:string,b:string,format:1|3|5):Match {const p=gameProbability(s.ratingSnapshot[a],s.ratingSnapshot[b]);return {id,stage,round,label,teamA:a,teamB:b,format,scoreA:null,scoreB:null,winner:null,status:'UNDECIDED',resultSource:null,modelProbabilityA:seriesProbability(p,format),modelProbabilityB:seriesProbability(1-p,format),locked:false}}
export function createSession(source:StrengthSource,ratings:Record<string,number>,tierList?:TierList,seed=Date.now()>>>0,seedAssignments:Record<string,number>=defaultSeedAssignments):SimulationSession {validateSeedAssignments(seedAssignments);const state:TournamentState={stage:'PLAY_IN',round:1,matches:[],swissRecords:{},swissQualified:[],swissEliminated:[],champion:null,playInWinner:null};const s:SimulationSession={id:crypto.randomUUID(),createdAt:new Date().toISOString(),strengthSource:source,systemModelVersion:source==='SYSTEM_MODEL'?worlds2026.modelVersion:undefined,tierListSnapshot:tierList?clone(tierList):undefined,seedAssignments:clone(seedAssignments),ratingSnapshot:clone(ratings),tournamentState:state,randomSeed:seed,rngState:seed,simulationStatus:'ACTIVE',scenarioMode:true};const p=sessionTeams(s).filter(t=>t.playIn).map(t=>t.id);state.matches=[makeMatch(s,'p1a','PLAY_IN',1,'入围赛 · 胜者组 1',p[0],p[3],5),makeMatch(s,'p1b','PLAY_IN',1,'入围赛 · 胜者组 2',p[1],p[2],5)];return s}
const match=(s:SimulationSession,id:string)=>{const m=s.tournamentState.matches.find(x=>x.id===id);if(!m)throw Error('比赛不存在');return m};
export function applyResult(s:SimulationSession,id:string,winner:string,scoreA:number,scoreB:number,source:'MANUAL'|'SIMULATION'|'OFFICIAL'):SimulationSession {const n=clone(s),m=match(n,id);if(m.resultSource==='OFFICIAL'&&source!=='OFFICIAL')throw Error('官方赛果已锁定');if(m.locked&&m.resultSource!=='OFFICIAL')throw Error('比赛已锁定，请先编辑该轮');if(winner!==m.teamA&&winner!==m.teamB)throw Error('获胜队伍无效');const need=(m.format+1)/2;if(Math.max(scoreA,scoreB)!==need||Math.min(scoreA,scoreB)>=need||(scoreA>scoreB)!==(winner===m.teamA))throw Error('比分不符合赛制');m.scoreA=scoreA;m.scoreB=scoreB;m.winner=winner;m.status='COMPLETE';m.resultSource=source;m.locked=source==='OFFICIAL';return n}
export function clearResult(s:SimulationSession,id:string):SimulationSession {const n=clone(s),m=match(n,id);if(m.resultSource==='OFFICIAL')throw Error('官方赛果不可修改');if(m.locked)throw Error('请先编辑该轮');m.scoreA=null;m.scoreB=null;m.winner=null;m.status='UNDECIDED';m.resultSource=null;return n}
export function editPreviousRound(s:SimulationSession,id:string):SimulationSession {const n=clone(s),m=match(n,id);if(m.resultSource==='OFFICIAL')throw Error('官方赛果不可修改');const order=(x:Match)=>x.stage==='PLAY_IN'?x.round:x.stage==='SWISS'?10+x.round:20+x.round;const cutoff=order(m);n.tournamentState.matches=n.tournamentState.matches.filter(x=>order(x)<=cutoff);for(const x of n.tournamentState.matches)if(order(x)===cutoff&&x.resultSource!=='OFFICIAL')x.locked=false;n.tournamentState.stage=m.stage;n.tournamentState.round=m.round;n.tournamentState.champion=null;n.simulationStatus='ACTIVE';rebuildDerived(n);return n}
function rebuildDerived(s:SimulationSession){const st=s.tournamentState;st.playInWinner=(st.matches.find(m=>m.id==='p5')??st.matches.find(m=>m.id==='p4'))?.winner??null;const direct=sessionTeams(s).filter(t=>!t.playIn).map(t=>t.id);const ids=st.playInWinner?[...direct,st.playInWinner]:[];st.swissRecords=Object.fromEntries(ids.map(id=>[id,{wins:0,losses:0}]));for(const m of st.matches.filter(m=>m.stage==='SWISS'&&m.status==='COMPLETE')){st.swissRecords[m.winner!].wins++;st.swissRecords[m.winner===m.teamA?m.teamB:m.teamA].losses++}st.swissQualified=ids.filter(id=>st.swissRecords[id].wins>=worlds2026.winsToAdvance);st.swissEliminated=ids.filter(id=>st.swissRecords[id].losses>=worlds2026.lossesToEliminate)}
function scoreSeries(s:SimulationSession,m:Match){const need=(m.format+1)/2,p=gameProbability(s.ratingSnapshot[m.teamA],s.ratingSnapshot[m.teamB]);let a=0,b=0;while(a<need&&b<need){if(randomNext(s)<p)a++;else b++}m.scoreA=a;m.scoreB=b;m.winner=a>b?m.teamA:m.teamB;m.status='COMPLETE';m.resultSource='SIMULATION'}
export function simulateRemaining(s:SimulationSession):SimulationSession {const n=clone(s),st=n.tournamentState;for(const m of st.matches.filter(m=>m.stage===st.stage&&m.round===st.round&&m.status==='UNDECIDED'))scoreSeries(n,m);return n}
function playInNext(s:SimulationSession){const st=s.tournamentState,p=(id:string)=>match(s,id);if(st.round===1){st.round=2;st.matches.push(makeMatch(s,'p2u','PLAY_IN',2,'入围赛 · 胜者组决赛',p('p1a').winner!,p('p1b').winner!,5),makeMatch(s,'p2l','PLAY_IN',2,'入围赛 · 败者组 1',p('p1a').winner===p('p1a').teamA?p('p1a').teamB:p('p1a').teamA,p('p1b').winner===p('p1b').teamA?p('p1b').teamB:p('p1b').teamA,5));return}if(st.round===2){st.round=3;const u=p('p2u'),loser=u.winner===u.teamA?u.teamB:u.teamA;st.matches.push(makeMatch(s,'p3','PLAY_IN',3,'入围赛 · 败者组决赛',loser,p('p2l').winner!,5));return}if(st.round===3){st.round=4;st.matches.push(makeMatch(s,'p4','PLAY_IN',4,'入围赛 · 晋级决赛',p('p2u').winner!,p('p3').winner!,worlds2026.seriesFormats.playIn));return}if(st.round===4&&worlds2026.playInGrandFinalReset&&p('p4').winner===p('p4').teamB){st.round=5;st.matches.push(makeMatch(s,'p5','PLAY_IN',5,'入围赛 · 决赛重赛',p('p4').teamA,p('p4').teamB,worlds2026.seriesFormats.playIn));return}st.playInWinner=st.round===5?p('p5').winner:p('p4').winner;st.stage='SWISS';st.round=1;rebuildDerived(s);drawSwiss(s)}
function pairPool(ids:string[],s:SimulationSession,avoidRegion:boolean):[string,string][]|null{const past=new Set(s.tournamentState.matches.filter(m=>m.stage==='SWISS').map(m=>[m.teamA,m.teamB].sort().join('|')));const search=(remaining:string[]):[string,string][]|null=>{if(!remaining.length)return [];const a=remaining[0];for(const b of shuffle(remaining.slice(1),s)){if(worlds2026.drawRestrictions.noRematch&&past.has([a,b].sort().join('|')))continue;if(avoidRegion&&teams.find(t=>t.id===a)?.region===teams.find(t=>t.id===b)?.region)continue;if(worlds2026.drawRestrictions.seedRestriction&&s.tournamentState.round===1&&sessionTeams(s).find(t=>t.id===a)?.seed===sessionTeams(s).find(t=>t.id===b)?.seed)continue;const tail=search(remaining.filter(x=>x!==a&&x!==b));if(tail)return [[a,b],...tail]}return null};return search(shuffle(ids,s))}
export function drawSwiss(s:SimulationSession){const st=s.tournamentState,active=Object.keys(st.swissRecords).filter(id=>st.swissRecords[id].wins<3&&st.swissRecords[id].losses<3);const pools=new Map<string,string[]>();for(const id of active){const r=st.swissRecords[id],key=`${r.wins}-${r.losses}`;pools.set(key,[...(pools.get(key)??[]),id])}let index=0;for(const [pool,ids] of pools){const pairs=pairPool(ids,s,worlds2026.drawRestrictions.avoidSameRegion)??pairPool(ids,s,false);if(!pairs)throw Error(`瑞士轮 ${pool} 分组无法满足无重赛抽签，请调整规则配置`);for(const [a,b] of pairs){const record=st.swissRecords[a];const format:1|3=record.wins===2||record.losses===2?worlds2026.seriesFormats.swissDecider:worlds2026.seriesFormats.swissEarly;st.matches.push(makeMatch(s,`s${st.round}-${++index}`,'SWISS',st.round,`瑞士轮 · ${pool} 组`,a,b,format))}}}
function knockoutNext(s:SimulationSession){const st=s.tournamentState,completed=st.matches.filter(m=>m.stage==='KNOCKOUT'&&m.round===st.round);if(st.round===3){st.champion=completed[0].winner;st.stage='CHAMPION';s.simulationStatus='COMPLETE';return}const winners=completed.map(m=>m.winner!);st.round++;const label=st.round===2?'半决赛':'总决赛';for(let i=0;i<winners.length;i+=2)st.matches.push(makeMatch(s,`k${st.round}-${i/2+1}`,'KNOCKOUT',st.round,label,winners[i],winners[i+1],worlds2026.seriesFormats.knockout))}
export function advance(s:SimulationSession):SimulationSession {const n=clone(s),st=n.tournamentState;if(st.stage==='CHAMPION')return n;const current=st.matches.filter(m=>m.stage===st.stage&&m.round===st.round);if(!current.length||current.some(m=>m.status!=='COMPLETE'))throw Error('请先决定本轮全部比赛');current.forEach(m=>m.locked=true);if(st.stage==='PLAY_IN')playInNext(n);else if(st.stage==='SWISS'){rebuildDerived(n);if(st.swissQualified.length===8){st.stage='KNOCKOUT';st.round=1;const q=shuffle(st.swissQualified,n);for(let i=0;i<8;i+=2)st.matches.push(makeMatch(n,`k1-${i/2+1}`,'KNOCKOUT',1,'四分之一决赛',q[i],q[i+1],worlds2026.seriesFormats.knockout))}else {st.round++;if(st.round>5)throw Error('瑞士轮晋级队伍数量异常');drawSwiss(n)}}else knockoutNext(n);return n}
export function simulateEntireWorlds(s:SimulationSession):SimulationSession {let n=clone(s),guard=0;while(n.tournamentState.stage!=='CHAMPION'&&guard++<20){n=simulateRemaining(n);n=advance(n)}if(n.tournamentState.stage!=='CHAMPION')throw Error('模拟未能完成');return n}
export class PlayInSimulator { static simulateRemaining=simulateRemaining }
export class SwissSimulator { static draw=drawSwiss; static simulateRemaining=simulateRemaining }
export class KnockoutSimulator { static simulateRemaining=simulateRemaining }
export class WorldsSimulator { static create=createSession; static simulateEntire=simulateEntireWorlds }
// Forks an independent hypothesis; the official source session remains untouched.
export function forkOfficialScenario(s:SimulationSession,id:string):SimulationSession {const original=match(s,id);if(original.resultSource!=='OFFICIAL')throw Error('这场比赛没有官方赛果');const n=clone(s);n.id=crypto.randomUUID();n.createdAt=new Date().toISOString();n.scenarioMode=true;const target=match(n,id);target.resultSource='MANUAL';target.locked=false;return editPreviousRound(n,id)}
