import {teamSnapshotMetadata} from './teamSnapshot';
import {riotGprSnapshot} from './gprSnapshot';
import type {SimulationSession} from './types';
import {simulateEntireWorlds} from './engine';
import {SIMULATION_COUNTS} from './oddsConfig';
import {tournamentStateHash,strengthVersion} from './oddsMetadata';
import {worlds2026} from './worlds2026';
export function runMonteCarloFromState(session:SimulationSession,iterations:number=SIMULATION_COUNTS.preview,seed=12345){const counts:Record<string,number>={};const knockoutCounts:Record<string,number>={};const semifinalCounts:Record<string,number>={};const finalCounts:Record<string,number>={};let completed=0;for(let i=0;i<iterations;i++){try{const sample:SimulationSession=JSON.parse(JSON.stringify(session));sample.rngState=(seed+i*7919)>>>0;const result=simulateEntireWorlds(sample);const winner=result.tournamentState.champion!;counts[winner]=(counts[winner]??0)+1;for(const id of result.tournamentState.swissQualified)knockoutCounts[id]=(knockoutCounts[id]??0)+1;for(const m of result.tournamentState.matches.filter(m=>m.stage==='KNOCKOUT'&&m.round>=2)){const target=m.round===2?semifinalCounts:finalCounts;for(const id of [m.teamA,m.teamB])target[id]=(target[id]??0)+1}completed++}catch{/* Unsatisfiable configured draw excluded; caller receives sample count. */}}return {probabilities:Object.fromEntries(Object.entries(counts).map(([id,count])=>[id,count/Math.max(completed,1)])),knockoutProbabilities:Object.fromEntries(Object.entries(knockoutCounts).map(([id,count])=>[id,count/Math.max(completed,1)])),semifinalProbabilities:Object.fromEntries(Object.entries(semifinalCounts).map(([id,count])=>[id,count/Math.max(completed,1)])),finalProbabilities:Object.fromEntries(Object.entries(finalCounts).map(([id,count])=>[id,count/Math.max(completed,1)])),iterations:completed,metadata:{teamSnapshotDate:teamSnapshotMetadata.snapshotUpdatedAt,gprSnapshotDate:riotGprSnapshot.sourceUpdatedAt,simulationCount:completed,requestedCount:iterations,generatedAt:new Date().toISOString(),modelVersion:session.systemModelVersion??worlds2026.modelVersion,strengthVersion:strengthVersion(session),tournamentStateHash:tournamentStateHash(session)}}}
export const runMonteCarlo=runMonteCarloFromState;
