import {validateSnapshots} from '../lib/sim/validateSnapshots.ts';
import {GprProbabilityModel} from '../lib/sim/gprProbability.ts';
import {defaultSeedAssignments} from '../lib/sim/seedAssignments.ts';
import assert from 'node:assert/strict';
import {createSession,applyResult,simulateRemaining,advance,simulateEntireWorlds,editPreviousRound,forkOfficialScenario} from '../lib/sim/engine.ts';
import {SystemRatingProvider,defaultTierList,generateRatingsFromTierList,gameProbability,validateTierList} from '../lib/sim/ratings.ts';
import {runMonteCarloFromState} from '../lib/sim/monteCarlo.ts';
import {teams} from '../lib/sim/data.ts';
import {RiotGprProvider,GprRatingAdapter} from '../lib/sim/riotGpr.ts';
import {ratingConfig} from '../lib/sim/ratingConfig.ts';
import {precomputedOdds,assertPrecomputedOddsCurrent} from '../lib/sim/precomputed.ts';
import {tournamentStateHash} from '../lib/sim/oddsMetadata.ts';
import {SIMULATION_COUNTS,formatProbability} from '../lib/sim/oddsConfig.ts';
try{
 assert.equal(teams.length,19);assert.equal(new Set(teams.map(t=>t.id)).size,19);
 assert.deepEqual(teams.filter(t=>t.region==='LPL').sort((a,b)=>a.seed-b.seed).map(t=>t.id),['AL','BLG','TES','IG']);
 assert.deepEqual(teams.filter(t=>t.region==='LCK').sort((a,b)=>a.seed-b.seed).map(t=>t.id),['GEN','HLE','T1','DK']);
 assert.deepEqual(teams.filter(t=>t.region==='LEC').sort((a,b)=>a.seed-b.seed).map(t=>t.id),['G2','MKOI','KC']);
 assert.deepEqual(teams.filter(t=>t.playIn).map(t=>t.id),['KC','MVK','C9','TBD-CBLOL']);
 assert.ok(!teams.some(t=>t.id==='JDG'));
 const ratings=new SystemRatingProvider().getRatings();
 const gpr=new RiotGprProvider();assert.equal(gpr.status,'CACHED');assert.deepEqual(gpr.get('HLE'),{rank:1,score:1540});assert.equal(teams.find(t=>t.id==='HLE').officialGprScore,1540);
 assert.equal(ratings.HLE,ratingConfig.gpr.referenceRating+(1540-ratingConfig.gpr.referenceScore)*ratingConfig.gpr.scoreScale);
 assert.equal(ratings['TBD-CBLOL'],teams.find(t=>t.id==='TBD-CBLOL').rating);
 const empty=new RiotGprProvider({entries:{},sourceUrl:'',sourceUpdatedAt:'',strengthVersion:'empty'});assert.equal(empty.status,'FALLBACK');assert.equal(new GprRatingAdapter(empty).rating(teams[0]),teams[0].rating);
 const summary=validateSnapshots();assert.equal(summary.confirmed,18);assert.equal(summary.matched,18);assert.equal(summary.fallback,1);
 assert.equal(teams.find(t=>t.id==='C9').officialGprScore,1335);assert.equal(teams.find(t=>t.id==='C9').officialSeed,null);
 assert.throws(()=>validateSnapshots([...teams.slice(0,18),teams[0]]),/Duplicate/);
 assert.throws(()=>validateSnapshots(teams.map((t,i)=>i===0?{...t,slug:teams[1].slug}:t)),/Duplicate/);
 assert.throws(()=>validateSnapshots(teams.slice(1)),/19 teams/);
 assert.throws(()=>validateSnapshots(teams,{HLE:{rank:1,score:NaN}}),/Invalid GPR/);
 assert.throws(()=>validateSnapshots(teams.map((t,i)=>i===0?{...t,gprKey:null}:t)),/mapping/);
 assert.throws(()=>validateSnapshots(teams.map((t,i)=>i===0?{...t,gprKey:teams[1].gprKey}:t)),/Duplicate/);
 assert.equal(validateSnapshots(teams,{}).fallback,19);
 const probabilityModel=new GprProbabilityModel();assert.equal(probabilityModel.probability(1500,1500),0.5);
 let last=0.5;for(const d of [1,5,10,20,50,100,200]){const p=probabilityModel.probability(1500+d,1500);assert.ok(p>last);last=p;assert.ok(Math.abs(p+probabilityModel.probability(1500,1500+d)-1)<1e-12)}
 assert.ok(probabilityModel.probability(1540,1519)<0.55);
 assert.throws(()=>new GprProbabilityModel(-1));assert.throws(()=>probabilityModel.probability(NaN,1500));
 for(const a of teams.filter(t=>t.officialGprScore)){for(const b of teams.filter(t=>t.officialGprScore)){assert.ok(Math.abs(gameProbability(ratings[a.id],ratings[b.id])-probabilityModel.probability(a.officialGprScore,b.officialGprScore))<1e-12)}}
 const alternateSeeds={...defaultSeedAssignments,LYON:3,C9:1,LOS:2,'TBD-CBLOL':1};
 const alternate=simulateEntireWorlds(createSession('SYSTEM_MODEL',ratings,undefined,42,alternateSeeds));assert.ok(alternate.tournamentState.champion);assert.deepEqual(alternate.tournamentState.matches.filter(m=>m.stage==='PLAY_IN'&&m.round===1).flatMap(m=>[m.teamA,m.teamB]).sort(),['KC','MVK','LYON','LOS'].sort());
 assert.throws(()=>createSession('SYSTEM_MODEL',ratings,undefined,42,{...defaultSeedAssignments,C9:1}),/不重复/);
 const base=createSession('SYSTEM_MODEL',ratings,undefined,42);
 assertPrecomputedOddsCurrent();assert.equal(precomputedOdds.metadata.simulationCount,SIMULATION_COUNTS.production);assert.equal(precomputedOdds.metadata.teamSnapshotDate,'2026-09-30');assert.equal(precomputedOdds.metadata.gprSnapshotDate,'2026-09-29');
 const published=createSession('SYSTEM_MODEL',ratings,undefined,2026);assert.equal(precomputedOdds.metadata.tournamentStateHash,tournamentStateHash(published));
 assert.equal(formatProbability(0.0005),'<0.1%');assert.equal(formatProbability(0.184),'18.4%');
 const full=simulateEntireWorlds(base);assert.ok(full.tournamentState.champion);assert.equal(full.simulationStatus,'COMPLETE');
 const first=base.tournamentState.matches[0];const manual=applyResult(base,first.id,first.teamA,3,1,'MANUAL');const mixed=simulateRemaining(manual);assert.equal(mixed.tournamentState.matches[0].resultSource,'MANUAL');assert.equal(mixed.tournamentState.matches[0].scoreB,1);assert.equal(mixed.tournamentState.matches[1].resultSource,'SIMULATION');
 const official=applyResult(base,first.id,first.teamA,3,0,'OFFICIAL');assert.throws(()=>applyResult(official,first.id,first.teamB,0,3,'MANUAL'));const scenario=forkOfficialScenario(official,first.id);assert.equal(official.tournamentState.matches[0].resultSource,'OFFICIAL');assert.equal(scenario.tournamentState.matches[0].locked,false);assert.equal(applyResult(scenario,first.id,first.teamB,0,3,'MANUAL').tournamentState.matches[0].winner,first.teamB);
 const played=simulateEntireWorlds(manual);assert.equal(played.tournamentState.matches[0].resultSource,'MANUAL');assert.equal(played.tournamentState.matches[0].scoreB,1);
 const swissStart=(()=>{let s=createSession('SYSTEM_MODEL',ratings,undefined,42);while(s.tournamentState.stage==='PLAY_IN')s=advance(simulateRemaining(s));return s})();
 const swissMatches=swissStart.tournamentState.matches.filter(m=>m.stage==='SWISS');let swiss=swissStart;for(let i=0;i<swissMatches.length/2;i++){const m=swissMatches[i];swiss=applyResult(swiss,m.id,m.teamA,1,0,'MANUAL')}swiss=simulateRemaining(swiss);swiss=advance(swiss);assert.equal(swiss.tournamentState.stage,'SWISS');assert.equal(swiss.tournamentState.round,2);assert.equal(Object.values(swiss.tournamentState.swissRecords).reduce((a,r)=>a+r.wins,0),8);
 const edited=editPreviousRound(swiss,swissMatches[0].id);assert.equal(edited.tournamentState.round,1);assert.equal(edited.tournamentState.matches.some(m=>m.stage==='SWISS'&&m.round===2),false);assert.equal(edited.tournamentState.matches.find(m=>m.id===swissMatches[0].id).locked,false);
 const again=simulateEntireWorlds(base);assert.equal(again.tournamentState.champion,full.tournamentState.champion);assert.deepEqual(again.tournamentState.matches.map(m=>[m.winner,m.scoreA,m.scoreB]),full.tournamentState.matches.map(m=>[m.winner,m.scoreA,m.scoreB]));
 const mcRepeatA=runMonteCarloFromState(base,50,42),mcRepeatB=runMonteCarloFromState(base,50,42);assert.deepEqual(mcRepeatA.probabilities,mcRepeatB.probabilities);assert.equal(mcRepeatA.metadata.tournamentStateHash,mcRepeatB.metadata.tournamentStateHash);assert.deepEqual(mcRepeatA.semifinalProbabilities,mcRepeatB.semifinalProbabilities);assert.notEqual(tournamentStateHash(base),tournamentStateHash({...base,seedAssignments:alternateSeeds}));
 const tier=defaultTierList();assert.equal(validateTierList(tier),null);const custom=generateRatingsFromTierList(tier);assert.equal(custom[tier.S[0]],ratingConfig.tierBase.S+((tier.S.length-1)/2)*ratingConfig.withinTierStep);const moved={...tier,S:[...tier.S].reverse()};const altered=generateRatingsFromTierList(moved);assert.notEqual(gameProbability(custom[tier.S[0]],custom[tier.S[1]]),gameProbability(altered[tier.S[0]],altered[tier.S[1]]));const mc=runMonteCarloFromState(manual,50,42);assert.ok(mc.iterations>0);const mcOther=runMonteCarloFromState(createSession('CUSTOM_TIER_LIST',altered,moved,42),50,42);assert.ok(mcOther.iterations>0);assert.notDeepEqual(mc.probabilities,mcOther.probabilities);
 console.log('关键场景通过：完整赛事、手动优先、瑞士轮、回退、GPR 转换与缺失回退、自定义评分、Monte Carlo 复现、10 万次赛前快照。');
}catch(e){console.error(e);process.exitCode=1}
