'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {teams,teamById} from '../../../lib/sim/data';
import {createSession} from '../../../lib/sim/engine';
import {defaultTierList,generateRatingsFromTierList,seriesProbability,gameProbability,SystemRatingProvider,validateTierList} from '../../../lib/sim/ratings';
import {runMonteCarloFromState} from '../../../lib/sim/monteCarlo';
import {worlds2026} from '../../../lib/sim/worlds2026';
import type {StrengthSource,Tier,TierList} from '../../../lib/sim/types';
import {TeamIdentity,RegionBadge} from '../../../components/tournament/team-identity';
import {ProbabilityBar} from '../../../components/tournament/probability-bar';

const tiers:Tier[]=['S','A','B','C','D'];
export default function NewSimulation(){
 const router=useRouter();
 const [source,setSource]=useState<StrengthSource>('SYSTEM_MODEL');
 const [tierList,setTierList]=useState<TierList>(defaultTierList);
 const [error,setError]=useState('');
 const [dragged,setDragged]=useState<string|null>(null);
 const [preview,setPreview]=useState<Record<string,number>|null>(null);
 const ratings=useMemo(()=>source==='SYSTEM_MODEL'?new SystemRatingProvider().getRatings():generateRatingsFromTierList(tierList),[source,tierList]);
 const sorted=useMemo(()=>[...teams].sort((a,b)=>ratings[b.id]-ratings[a.id]),[ratings]);
 function move(id:string,tier:Tier,index?:number){setTierList(prev=>{const next:TierList={S:[...prev.S],A:[...prev.A],B:[...prev.B],C:[...prev.C],D:[...prev.D]};for(const k of tiers)next[k]=next[k].filter(x=>x!==id);next[tier].splice(index??next[tier].length,0,id);return next});setPreview(null)}
 function start(){const err=validateTierList(tierList);if(source==='CUSTOM_TIER_LIST'&&err){setError(err);return}const session=createSession(source,ratings,source==='CUSTOM_TIER_LIST'?tierList:undefined);localStorage.setItem('worlds2026-session',JSON.stringify(session));router.push('/simulator')}
 function odds(){setError('');try{const session=createSession(source,ratings,source==='CUSTOM_TIER_LIST'?tierList:undefined,12345);setPreview(runMonteCarloFromState(session,300,27182).probabilities)}catch(e){setError(e instanceof Error?e.message:'无法计算概率')}}
 return <main className="shell"><div className="page-head"><div><div className="eyebrow">NEW SIMULATION / STEP 01</div><h1>建立你的 Worlds</h1><p>先选择实力依据。开始后评分会保存为本次模拟的快照。</p></div></div><div className="tabs"><button className={`tab ${source==='SYSTEM_MODEL'?'active':''}`} onClick={()=>{setSource('SYSTEM_MODEL');setPreview(null)}}>系统模型</button><button className={`tab ${source==='CUSTOM_TIER_LIST'?'active':''}`} onClick={()=>{setSource('CUSTOM_TIER_LIST');setPreview(null)}}>自定义 Tier List</button></div><div style={{height:18}}/>
 {source==='SYSTEM_MODEL'?<div className="grid grid-2"><section className="panel"><div className="eyebrow">SYSTEM MODEL</div><h2>Elo 示例模型 v1.0</h2><p className="muted">已纳入 19 个示例候选队。当前评分是演示数据，正式参赛队与种子待官方确认。</p><div className="note">系统 Rating 与夺冠概率由本站计算，不是 Riot 官方预测。</div><p className="fine">模型版本：{worlds2026.modelVersion} · 示例资料更新：2026-09-28</p></section><section className="panel"><h2>评分预览</h2>{sorted.slice(0,5).map((t,i)=><div className="leader" key={t.id}><span className="home-team-leader"><span className="rank-num">{i+1}</span><TeamIdentity teamId={t.id} size={32}/></span><b className="accent">{ratings[t.id]}</b></div>)}</section></div>:<><div className="section-title"><h2>调整 19 支队伍的实力层级</h2><div className="action-row"><button className="button small ghost" onClick={()=>{setTierList(defaultTierList());setPreview(null)}}>按系统排名重置</button></div></div><p className="fine">拖动队伍到其他 Tier 或同层调整位置；也可使用右侧菜单移动。每层从上到下依次递减 20 分。</p><div className="tier-grid">{tiers.map(tier=><div className="tier-col" key={tier} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(dragged)move(dragged,tier);setDragged(null)}}><h3>{tier} TIER</h3>{tierList[tier].map((id,index)=><div key={id} draggable onDragStart={()=>setDragged(id)} onDragEnd={()=>setDragged(null)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();event.preventDefault();if(dragged)move(dragged,tier,index);setDragged(null)}} className="team-chip"><span className="tier-chip-details"><TeamIdentity teamId={id} size={30} showName showRegion={false}/></span><span className="tier-chip-meta"><RegionBadge region={teamById(id)?.region}/><span className="tier-chip-rating">{ratings[id]}</span></span><select aria-label={`移动 ${id} 到 Tier`} value={tier} onChange={event=>move(id,event.target.value as Tier)}>{tiers.map(t=><option key={t} value={t}>{t}</option>)}</select></div>)}</div>)}</div><div className="section-title"><h2>实力预览</h2><button className="button small secondary" onClick={odds}>计算夺冠概率</button></div><div className="panel" style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>队伍</th><th>Tier</th><th>自定义 Rating</th><th>对阵榜首 Bo1 / Bo3 / Bo5</th><th>夺冠概率</th></tr></thead><tbody>{sorted.map(team=>{const probability=gameProbability(ratings[team.id],ratings[sorted[0].id]);return <tr key={team.id}><td><TeamIdentity teamId={team.id} size={30} showRegion={false}/></td><td>{tiers.find(tier=>tierList[tier].includes(team.id))}</td><td className="accent">{ratings[team.id]}</td><td>{[1,3,5].map(format=>Math.round(seriesProbability(probability,format as 1|3|5)*100)+'%').join(' / ')}</td><td className="rank-prob-cell"><strong>{preview?`${((preview[team.id]??0)*100).toFixed(1)}%`:'—'}</strong>{preview&&<ProbabilityBar a={preview[team.id]??0}/>}</td></tr>})}</tbody></table></div><p className="fine">夺冠概率基于你的 Tier List，使用 300 次快速模拟；正式模拟中可重新计算。</p></>}
 {error&&<p role="alert" className="notice">{error}</p>}<div className="action-row" style={{marginTop:25}}><button className="button" onClick={start}>开始 Worlds 模拟 →</button><span className="fine">手动选比分与随机模拟可同时使用。</span></div></main>;
}
